config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get "/", to: "pages#home", as: "root"
  
  get "/admin", to: "pages#admin", as: "admin"
  get "/user", to: "pages#user", as: "user"

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


  get "payments/success", to: "payments#success"
  post "payments/webhook", to: "payments#webhook"

  get "/makes", to: "makes#index", as: "makes"
  post "/makes", to: "makes#create"
  get "/makes/new", to: "makes#new", as: "new_make"
  get "/makes/:id", to: "makes#show", as: "make"
  put "/makes/:id", to: "makes#update"
  patch "/makes/:id", to: "makes#update"
  delete "/makes/:id", to: "makes#destroy"
  get "/makes/:id/edit", to: "makes#edit", as: "edit_make"

  get "/colours", to: "colours#index", as: "colours"
  post "/colours", to: "colours#create"
  get "/colours/new", to: "colours#new", as: "new_colour"
  get "/colours/:id", to: "colours#show", as: "colour"
  put "/colours/:id", to: "colours#update"
  patch "/colours/:id", to: "colours#update"
  delete "/colours/:id", to: "colours#destroy"
  get "/colours/:id/edit", to: "colours#edit", as: "edit_colour"

  get "/conditions", to: "conditions#index", as: "conditions"
  post "/conditions", to: "conditions#create"
  get "/conditions/new", to: "conditions#new", as: "new_condition"
  get "/conditions/:id", to: "conditions#show", as: "condition"
  put "/conditions/:id", to: "conditions#update"
  patch "/conditions/:id", to: "conditions#update"
  delete "/conditions/:id", to: "conditions#destroy"
  get "/conditions/:id/edit", to: "conditions#edit", as: "edit_condition"

  get "/sizes", to: "sizes#index", as: "sizes"
  post "/sizes", to: "sizes#create"
  get "/sizes/new", to: "sizes#new", as: "new_size"
  get "/sizes/:id", to: "sizes#show", as: "size"
  put "/sizes/:id", to: "sizes#update"
  patch "/sizes/:id", to: "sizes#update"
  delete "/sizes/:id", to: "sizes#destroy"
  get "/sizes/:id/edit", to: "sizes#edit", as: "edit_size"

 

  get "*path", to: "pages#not_found", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

end

app/models/make.rb
class Make < ApplicationRecord
  has_many :listings
  validates :make, presence: true
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController

  load_and_authorize_resource

  def index
      @makes = Make.all
  end

  def show

  end

  def new
    @make = Make.new
  end

  

  def create
    
    make_params
    @make = Make.new( make_params )
    if @make.save
      redirect_to @make
    end 

  end

  def edit
    
  end

  def update
    
    if @make.update( make_params )
      redirect_to @make
    else 
      render :edit
    end
  end

  def destroy
      @make.destroy
      redirect_to makes_path
  end

  

  private

  def set_make
    id = params[ :id ]
    @make = Make.find( id )
  end


  def make_params
    params.require(:make).permit(:make)
  end
end

app/views/makes/_form.html.erb
<%= form_with(model: make, local: true) do |form| %>

<% if @make.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@make.errors.count, "Error") %> prohibited this form from being saved:</h2>
 
    <ul>
    <% @make.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>

    <div>
        <%= form.label :make %>
        <%= form.text_field :make, :required => true, :autofocus => true, :placeholder => "Which make would you like to add?"%>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/makes/edit.html.erb
Edit
<%= render 'form', make: @make %>

<%= link_to 'Listings', listings_path %>
<%= link_to 'Add New Listing', new_listing_path %>
<%= link_to 'Home', root_path %>

app/views/makes/index.html.erb
<h1>Makes</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @makes.each do |make| %>
    <tr>
      <td><%= make.make %></td>

      <td><%= link_to 'Edit', edit_make_path( make )%></td>
      <td><%= link_to 'Destroy', make_path( make ), method: :delete, data: { confirm: 'Are you sure you want to delete this, Punk?' } %></td>
      <% end %>
    </tr>
  </tbody>
</table>
<br>
<%= link_to 'Add New Make', new_make_path %>
<%= link_to 'Home', root_path %>

app/views/makes/new.html.erb
New Make
<%= render 'form', make: @make %>

<%= link_to 'Listings', listings_path %>
<%= link_to 'Add New Listing', new_listing_path %>
<%= link_to 'Home', root_path %>

app/views/makes/show.html.erb
<h1>Show Make</h1>

<p>
<strong>Make:</strong>
<%=@make.make%>
</p>

<td><%= link_to 'View All', makes_path( @make )%></td>
<td><%= link_to 'Edit', edit_make_path( @make )%></td>
<td><%= link_to 'Destroy', make_path( @make ), method: :delete, data: { confirm: 'Are you sure you want to delete this, Punk?' } %></td>
 