config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get "/", to: "pages#home", as: "root"
  
  get "/admin", to: "pages#admin", as: "admin"
  get "/user", to: "pages#user", as: "user"

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


  get "payments/success", to: "payments#success"
  post "payments/webhook", to: "payments#webhook"

  get "/makes", to: "makes#index", as: "makes"
  post "/makes", to: "makes#create"
  get "/makes/new", to: "makes#new", as: "new_make"
  get "/makes/:id", to: "makes#show", as: "make"
  put "/makes/:id", to: "makes#update"
  patch "/makes/:id", to: "makes#update"
  delete "/makes/:id", to: "makes#destroy"
  get "/makes/:id/edit", to: "makes#edit", as: "edit_make"

  get "/colours", to: "colours#index", as: "colours"
  post "/colours", to: "colours#create"
  get "/colours/new", to: "colours#new", as: "new_colour"
  get "/colours/:id", to: "colours#show", as: "colour"
  put "/colours/:id", to: "colours#update"
  patch "/colours/:id", to: "colours#update"
  delete "/colours/:id", to: "colours#destroy"
  get "/colours/:id/edit", to: "colours#edit", as: "edit_colour"

  get "/conditions", to: "conditions#index", as: "conditions"
  post "/conditions", to: "conditions#create"
  get "/conditions/new", to: "conditions#new", as: "new_condition"
  get "/conditions/:id", to: "conditions#show", as: "condition"
  put "/conditions/:id", to: "conditions#update"
  patch "/conditions/:id", to: "conditions#update"
  delete "/conditions/:id", to: "conditions#destroy"
  get "/conditions/:id/edit", to: "conditions#edit", as: "edit_condition"

  get "/sizes", to: "sizes#index", as: "sizes"
  post "/sizes", to: "sizes#create"
  get "/sizes/new", to: "sizes#new", as: "new_size"
  get "/sizes/:id", to: "sizes#show", as: "size"
  put "/sizes/:id", to: "sizes#update"
  patch "/sizes/:id", to: "sizes#update"
  delete "/sizes/:id", to: "sizes#destroy"
  get "/sizes/:id/edit", to: "sizes#edit", as: "edit_size"

 

  get "*path", to: "pages#not_found", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

end

app/views/pages/shared/_admin_nav_bar.html.erb
<nav class="navbar navbar-expand navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'View Dashboard', admin_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Manage Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'Listings', admin_path, class:"dropdown-item" %>
          <%= link_to 'Colours', colours_path, class:"dropdown-item" %>
          <%= link_to 'Makes', makes_path, class:"dropdown-item" %>
          <%= link_to 'Conditions', conditions_path, class:"dropdown-item" %>
          <%= link_to 'Sizes', sizes_path, class:"dropdown-item" %>
      </li>
  </div>
</nav>

app/views/pages/shared/_footer.html.erb
<div class="footer">
    <footer>
      <div class="footer-links">
        <div class="footer-link">
        <%=link_to root_path do%>
        <%= image_tag 'MKdark', alt:'logo image' %>
        <% end %>
        </div>
      </div>
      <div class="footer-tagline">
        <p>Made with <i class="fas fa-heart heart-logo"></i> &copy; Martyna Krawczyk 2019</p>
      </div>
    </footer>

app/views/pages/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Natu[re]Cycle</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <div class="navbar-nav w-100">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'View Listings', listings_path(@listing), class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sell a Bike', new_listing_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
    <%= link_to 'Edit profile', edit_user_registration_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
    <%= link_to "Logout", destroy_user_session_path, class:"nav-link", method: :delete %>
    </li>
    <% else %>
    <li class="nav-item">
    <%= link_to "Login", new_user_session_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
    <%= link_to "Sign up", new_user_registration_path, class:"nav-link"  %>
    </li>
    <% end %>
    </li>
    </ul>
    </div>
  </div>
</nav>

app/views/pages/shared/_user_nav_bar.html.erb
<nav class="navbar navbar-expand navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Manage My Listings', user_path, class:"nav-link" %>
      </li>
  </div>
</nav>

  