config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get "/", to: "pages#home", as: "root"
  
  get "/admin", to: "pages#admin", as: "admin"
  get "/user", to: "pages#user", as: "user"

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


  get "payments/success", to: "payments#success"
  post "payments/webhook", to: "payments#webhook"

  get "/makes", to: "makes#index", as: "makes"
  post "/makes", to: "makes#create"
  get "/makes/new", to: "makes#new", as: "new_make"
  get "/makes/:id", to: "makes#show", as: "make"
  put "/makes/:id", to: "makes#update"
  patch "/makes/:id", to: "makes#update"
  delete "/makes/:id", to: "makes#destroy"
  get "/makes/:id/edit", to: "makes#edit", as: "edit_make"

  get "/colours", to: "colours#index", as: "colours"
  post "/colours", to: "colours#create"
  get "/colours/new", to: "colours#new", as: "new_colour"
  get "/colours/:id", to: "colours#show", as: "colour"
  put "/colours/:id", to: "colours#update"
  patch "/colours/:id", to: "colours#update"
  delete "/colours/:id", to: "colours#destroy"
  get "/colours/:id/edit", to: "colours#edit", as: "edit_colour"

  get "/conditions", to: "conditions#index", as: "conditions"
  post "/conditions", to: "conditions#create"
  get "/conditions/new", to: "conditions#new", as: "new_condition"
  get "/conditions/:id", to: "conditions#show", as: "condition"
  put "/conditions/:id", to: "conditions#update"
  patch "/conditions/:id", to: "conditions#update"
  delete "/conditions/:id", to: "conditions#destroy"
  get "/conditions/:id/edit", to: "conditions#edit", as: "edit_condition"

  get "/sizes", to: "sizes#index", as: "sizes"
  post "/sizes", to: "sizes#create"
  get "/sizes/new", to: "sizes#new", as: "new_size"
  get "/sizes/:id", to: "sizes#show", as: "size"
  put "/sizes/:id", to: "sizes#update"
  patch "/sizes/:id", to: "sizes#update"
  delete "/sizes/:id", to: "sizes#destroy"
  get "/sizes/:id/edit", to: "sizes#edit", as: "edit_size"

 

  get "*path", to: "pages#not_found", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController

  load_and_authorize_resource

  def index
      @sizes = Size.all
  end

  def show

  end

  def new
    @size = Size.new
  end

  

  def create
    
    size_params
    @size = Size.new( size_params )
    if @size.save
      redirect_to @size
    end 

  end

  def edit
    
  end

  def update
    
    if @size.update( size_params )
      redirect_to @size
    else 
      render :edit
    end
  end

  def destroy
      @size.destroy
      redirect_to sizes_path
  end

  

  private

  def set_size
    id = params[ :id ]
    @size = Size.find( id )
  end


  def size_params
    params.require(:size).permit(:size)
  end
end

app/views/sizes/_form.html.erb
<%= form_with(model: size, local: true) do |form| %>

<% if @size.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@size.errors.count, "Error") %> prohibited this form from being saved:</h2>
 
    <ul>
    <% @size.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>

    <div>
        <%= form.label :size %>
        <%= form.text_field :size, :required => true, :autofocus => true, :placeholder => "Which size would you like to add?"%>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/sizes/edit.html.erb
Edit
<%= render 'form', size: @size %>

<%= link_to 'Listings', listings_path %>
<%= link_to 'Add New Listing', new_listing_path %>
<%= link_to 'Home', root_path %>

app/views/sizes/index.html.erb
<h1>Sizes</h1>

<table>
  <thead>
    <tr>
      <th>Sizes</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @sizes.each do |size| %>
    <tr>
      <td><%= size.size %></td>
      
      <td><%= link_to 'Edit', edit_size_path( size )%></td>
      <td><%= link_to 'Destroy', size_path( size ), method: :delete, data: { confirm: 'Are you sure you want to delete this, Punk?' } %></td>
      <% end %>
    </tr>
  </tbody>
</table>
<br>
<%= link_to 'Add New Size', new_size_path %>
<%= link_to 'Home', root_path %>

app/views/sizes/new.html.erb
New Size
<%= render 'form', size: @size %>

<%= link_to 'Listings', listings_path %>
<%= link_to 'Add New Listing', new_listing_path %>
<%= link_to 'Home', root_path %>

app/views/sizes/show.html.erb
<h1>Show Size</h1>

<p>
<strong>Sizes:</strong>
<%=@size.size%>
</p>

<td><%= link_to 'View All', sizes_path( @size )%></td>
<td><%= link_to 'Edit', edit_size_path( @size )%></td>
<td><%= link_to 'Destroy', size_path( @size ), method: :delete, data: { confirm: 'Are you sure you want to delete this, Punk?' } %></td>