config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get "/", to: "pages#home", as: "root"
  
  get "/admin", to: "pages#admin", as: "admin"
  get "/user", to: "pages#user", as: "user"

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


  get "payments/success", to: "payments#success"
  post "payments/webhook", to: "payments#webhook"

  get "/makes", to: "makes#index", as: "makes"
  post "/makes", to: "makes#create"
  get "/makes/new", to: "makes#new", as: "new_make"
  get "/makes/:id", to: "makes#show", as: "make"
  put "/makes/:id", to: "makes#update"
  patch "/makes/:id", to: "makes#update"
  delete "/makes/:id", to: "makes#destroy"
  get "/makes/:id/edit", to: "makes#edit", as: "edit_make"

  get "/colours", to: "colours#index", as: "colours"
  post "/colours", to: "colours#create"
  get "/colours/new", to: "colours#new", as: "new_colour"
  get "/colours/:id", to: "colours#show", as: "colour"
  put "/colours/:id", to: "colours#update"
  patch "/colours/:id", to: "colours#update"
  delete "/colours/:id", to: "colours#destroy"
  get "/colours/:id/edit", to: "colours#edit", as: "edit_colour"

  get "/conditions", to: "conditions#index", as: "conditions"
  post "/conditions", to: "conditions#create"
  get "/conditions/new", to: "conditions#new", as: "new_condition"
  get "/conditions/:id", to: "conditions#show", as: "condition"
  put "/conditions/:id", to: "conditions#update"
  patch "/conditions/:id", to: "conditions#update"
  delete "/conditions/:id", to: "conditions#destroy"
  get "/conditions/:id/edit", to: "conditions#edit", as: "edit_condition"

  get "/sizes", to: "sizes#index", as: "sizes"
  post "/sizes", to: "sizes#create"
  get "/sizes/new", to: "sizes#new", as: "new_size"
  get "/sizes/:id", to: "sizes#show", as: "size"
  put "/sizes/:id", to: "sizes#update"
  patch "/sizes/:id", to: "sizes#update"
  delete "/sizes/:id", to: "sizes#destroy"
  get "/sizes/:id/edit", to: "sizes#edit", as: "edit_size"

 

  get "*path", to: "pages#not_found", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

end

app/models/colour.rb
class Colour < ApplicationRecord
  has_many :listings

  validates :colour, presence: true
end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController

  load_and_authorize_resource

  def index
      @colours = Colour.all
  end

  def show

  end

  def new
    @colour = Colour.new
  end

  

  def create
    
    colour_params
    @colour = Colour.new( colour_params )
    if @colour.save
      redirect_to @colour
    end 

  end

  def edit
    
  end

  def update
    
    if @colour.update( colour_params )
      redirect_to @colour
    else 
      render :edit
    end
  end

  def destroy
      @colour.destroy
      redirect_to colours_path
  end

  

  private

  def set_colour
    id = params[ :id ]
    @colour = Colour.find( id )
  end


  def colour_params
    params.require(:colour).permit(:colour)
  end
end

app/views/colours/_form.html.erb
<%= form_with(model: colour, local: true) do |form| %>

<% if @colour.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@colour.errors.count, "Error") %> prohibited this form from being saved:</h2>
 
    <ul>
    <% @colour.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>

    <div>
        <%= form.label :colour %>
        <%= form.text_field :colour, :required => true, :autofocus => true, :placeholder => "Which colour would you like to add?", :pattern => "[^0-9]*"%>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/colours/edit.html.erb
Edit
<%= render 'form', colour: @colour %>

<%= link_to 'Listings', listings_path %>
<%= link_to 'Add New Listing', new_listing_path %>
<%= link_to 'Home', root_path %>

app/views/colours/index.html.erb
<h1>Colours</h1>

<table>
  <thead>
    <tr>
      <th>Colour</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @colours.each do |colour| %>
    <tr>
      <td><%= colour.colour %></td>

      <td><%= link_to 'Edit', edit_colour_path( colour )%></td>
      <td><%= link_to 'Destroy', colour_path( colour ), method: :delete, data: { confirm: 'Are you sure you want to delete this, Punk?' } %></td>
      <% end %>
    </tr>
  </tbody>
</table>
<br>
<%= link_to 'Add New Colour', new_colour_path %>
<%= link_to 'Home', root_path %>

app/views/colours/new.html.erb
New Make
<%= render 'form', colour: @colour %>

<%= link_to 'Listings', listings_path %>
<%= link_to 'Add New Listing', new_listing_path %>
<%= link_to 'Home', root_path %>

app/views/colours/show.html.erb
<h1>Show Colour</h1>

<p>
<strong>Colour:</strong>
<%=@colour.colour%>
</p>

<td><%= link_to 'View All', colours_path( @colour )%></td>
<td><%= link_to 'Edit', edit_colour_path( @colour )%></td>
<td><%= link_to 'Destroy', colour_path( @colour ), method: :delete, data: { confirm: 'Are you sure you want to delete this, Punk?' } %></td>